#!/usr/bin/env bash
# configure 404 page

apt-get update
apt-get -y install nginx
echo 'Hello World!' | tee /var/www/html/index.html
sed -i "48i\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | tee /var/www/html/404.html
sed -i "50i\\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
service nginx restart
service nginx reload
