#!/usr/bin/env bash
# Displays the content of /etc/passwd

while IFS=: read -r USERNAME PASSWORD ID GROUP_ID USER HOME_DIRECTORY COMMAND
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER"
done < "/etc/passwd"
