#!/usr/bin/env bash
# Displays Best school 10, and for the 9th itiration displays
#Best school and Hi on a new line

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$(( i+1 ))
done
