#!/usr/bin/env bash
# displays numbers from 1 to 10 and bad luck from china for the 4th iteration
# bad luck from japan for the 9th iteration
# and bad luck from italy for the 17th iteration

i=1
while [ $i -le 20 ]
do
	case $i in
		4) echo "$i"
		   echo "bad luck from China";;
		9) echo "$i"
		   echo "bad luck from Japan";;
		17) echo "$i"
		    echo "bad luck from Italy";;
		*) echo "$i"
	esac
	i=$(( i + 1 ))
done
