#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements :
## localhost resolves to 127.0.0.2
## facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.backup
cp /etc/hosts /etc/hosts.new
echo "127.0.0.2		  localhost" >> /etc/hosts.new
echo "8.8.8.8		  facebook.com" >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
rm /etc/hosts.new